workflows:
  ios-release-no-codesign:
    name: iOS Release (No Code Sign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.aplikasibalita"
    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get

      - name: Generate app icons
        script: |
          dart run flutter_launcher_icons

      - name: Build iOS release and create IPA (fixed)
        script: |
          # Build iOS release without codesigning
          flutter build ios --release --no-codesign
          
          # Go to build output
          cd build/ios/iphoneos
          
          # Remove old Payload if exists
          rm -rf Payload
          
          # Make sure Runner.app exists
          if [ ! -d "Runner.app" ]; then
            echo "Error: Runner.app not found! Build failed."
            exit 1
          fi
          
          # Create Payload folder and copy Runner.app
          mkdir Payload
          cp -r Runner.app Payload/
          
          # Zip Payload into IPA with professional name
          zip -r $CM_BUILD_DIR/artifacts/Balitacare.ipa Payload
          
          # Clean up Payload folder
          rm -rf Payload
          
          # Verify IPA content
          unzip -l $CM_BUILD_DIR/artifacts/Balitacare.ipa

    artifacts:
      - $CM_BUILD_DIR/artifacts/*.ipa

    publishing:
      email:
        recipients:
          - onlymarfa69@gmail.com
        notify:
          success: true
          failure: true
