workflows:
  ios-release-no-shorebird:
    name: iOS Release (No Code Sign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.aplikasibalita"
    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get

      - name: Generate app icons
        script: |
          dart run flutter_launcher_icons

      - name: Build iOS release and create IPA
        script: |
          # Build iOS release without codesigning
          flutter build ios --release --no-codesign
          
          # Make sure artifacts directory exists
          mkdir -p $CM_BUILD_DIR/artifacts
          
          # Go to build folder
          cd build/ios/iphoneos
          
          # Remove old Payload if exists
          rm -rf Payload
          
          # Create Payload folder and copy Runner.app
          mkdir Payload
          cp -r Runner.app Payload/
          
          # Create IPA with professional name
          zip -r $CM_BUILD_DIR/artifacts/Balitacare.ipa Payload
          
          # Clean up Payload folder
          rm -rf Payload
          
          # Verify IPA was created
          ls -lh $CM_BUILD_DIR/artifacts/

    artifacts:
      - $CM_BUILD_DIR/artifacts/*.ipa

    publishing:
      email:
        recipients:
          - onlymarfa69@gmail.com
        notify:
          success: true
          failure: true
