workflows:
  ios-release-altstore:
    name: iOS Release (AltStore Ready)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        # Add your Codemagic environment variable group here
        # - app_store_credentials
      ios_signing:
        distribution_type: development
        bundle_identifier: com.aldayanday.balitacare
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.aldayanday.balitacare"
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
          
      - name: Fetch signing files (auto)
        script: |
          # This will automatically create development certificate if needed
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --create
          
      - name: Use signing files
        script: |
          keychain add-certificates
          xcode-project use-profiles
          
      - name: Clean project
        script: |
          flutter clean
          flutter pub get

      - name: Generate app icons
        script: |
          dart run flutter_launcher_icons

      - name: Build signed IPA for AltStore
        script: |
          # Build iOS with development signing
          flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist
          
          # Copy IPA to artifacts
          mkdir -p $CM_BUILD_DIR/artifacts
          cp build/ios/ipa/*.ipa $CM_BUILD_DIR/artifacts/Balitacare.ipa
          
          # Verify
          ls -lh $CM_BUILD_DIR/artifacts/

    artifacts:
      - $CM_BUILD_DIR/artifacts/*.ipa

    publishing:
      email:
        recipients:
          - onlymarfa69@gmail.com
        notify:
          success: true
          failure: true
