workflows:
  ios-release-altstore:
    name: iOS Release (AltStore Ready)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.aplikasibalita"
    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get

      - name: Generate app icons
        script: |
          dart run flutter_launcher_icons

      - name: Build iOS and create IPA (AltStore-ready)
        script: |
          set -e
          echo "Building iOS (no codesign)"
          flutter build ios --release --no-codesign

          ARTIFACTS_DIR="$CM_BUILD_DIR/artifacts"
          mkdir -p "$ARTIFACTS_DIR"

          # Find the .app produced by the build (search under build/ios)
          APP_PATH=$(find build/ios -type d -name "Runner.app" | head -n 1 || true)
          echo "Found app path: $APP_PATH"

          if [ -z "$APP_PATH" ]; then
            echo "ERROR: Runner.app not found. Listing build/ios contents for debugging:" >&2
            find build/ios -maxdepth 3 -type d -print || true
            exit 2
          fi

          # Prepare Payload and copy the .app
          PAYLOAD_DIR="$(pwd)/Payload"
          rm -rf "$PAYLOAD_DIR"
          mkdir -p "$PAYLOAD_DIR"
          cp -R "$APP_PATH" "$PAYLOAD_DIR/"

          # Ensure Info.plist exists inside the app (basic validation)
          if [ ! -f "$PAYLOAD_DIR/Runner.app/Info.plist" ]; then
            echo "ERROR: Info.plist missing inside Runner.app" >&2
            ls -la "$PAYLOAD_DIR/Runner.app" || true
            exit 3
          fi

          IPA_NAME="Balitacare.ipa"
          IPA_PATH="$ARTIFACTS_DIR/$IPA_NAME"

          # Create IPA (zip the Payload directory)
          (cd "$PAYLOAD_DIR" && zip -r "$IPA_PATH" Payload) || { echo "zip failed"; exit 4; }

          # Check IPA size (sanity check)
          echo "IPA produced:" && ls -lh "$IPA_PATH" || true

          # Clean
          rm -rf "$PAYLOAD_DIR"

    artifacts:
      - $CM_BUILD_DIR/artifacts/*.ipa

    publishing:
      email:
        recipients:
          - onlymarfa69@gmail.com
        notify:
          success: true
          failure: true
