workflows:
  ios-release-altstore:
    name: iOS Release (AltStore Ready)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.aplikasibalita"
    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get

      - name: Generate app icons
        script: |
          dart run flutter_launcher_icons

      - name: Build iOS and create IPA
        script: |
          # Build iOS release (no code sign)
          flutter build ios --release --no-codesign
          
          # Navigate to build folder
          cd build/ios/iphoneos
          
          # Make sure Payload folder exists and contains Runner.app
          mkdir -p Payload
          cp -r Runner.app Payload/
          
          # Create artifacts folder
          mkdir -p $CM_BUILD_DIR/artifacts
          
          # Zip Payload into IPA with professional name
          zip -r $CM_BUILD_DIR/artifacts/Balitacare.ipa Payload
          
          # Clean up Payload folder
          rm -rf Payload
          
          # Verify IPA
          ls -lh $CM_BUILD_DIR/artifacts/

    artifacts:
      - $CM_BUILD_DIR/artifacts/*.ipa

    publishing:
      email:
        recipients:
          - onlymarfa69@gmail.com
        notify:
          success: true
          failure: true
