workflows:
  ios-release-no-shorebird:
    name: iOS Release (No Code Sign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.example.aplikasibalita"
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles

      - name: Clean project
        script: |
          flutter clean
          flutter pub get

      - name: Generate app icons
        script: |
          dart run flutter_launcher_icons

      - name: Build iOS and create IPA
        script: |
          # Build without codesigning for development/testing
          flutter build ios --release --no-codesign
          
          # Create artifacts directory
          mkdir -p $CM_BUILD_DIR/artifacts
          
          # Create IPA manually without signing
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r $CM_BUILD_DIR/artifacts/Balitacare-unsigned.ipa Payload
          rm -rf Payload
          
          # Verify IPA was created
          ls -lh $CM_BUILD_DIR/artifacts/

    artifacts:
      - $CM_BUILD_DIR/artifacts/*.ipa
    
    publishing:
      email:
        recipients:
          - onlymarfa69@gmail.com
        notify:
          success: true
          failure: true
