name: aplikasibalita
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Animations
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.3.0
  curved_navigation_bar: ^1.0.6
  dropdown_button2: ^2.3.9
  flashy_flushbar: ^1.4.0
  flutter_screenutil: ^5.9.3
  quickalert: ^1.1.0
  marquee: ^2.2.3

  # File & Storage
  file_picker: ^8.0.5
  flutter_file_dialog: ^3.0.1
  open_file: ^3.5.4
  path_provider: ^2.1.4
  path: any
  saf: ^1.0.3+4
  permission_handler: ^10.4.5

  # Notifications & Intents
  flutter_local_notifications: ^18.0.1
  android_intent_plus: ^6.0.0

  # Database & Utils
  sqflite: ^2.3.3+1
  excel: ^4.0.6
  url_launcher: ^6.3.1

  # Calendar & Charts
  table_calendar: ^3.0.9
  month_year_picker: ^0.3.0+1
  syncfusion_flutter_charts: ^28.2.6
  syncfusion_flutter_datepicker: ^28.2.6
  fl_chart: ^0.71.0

  # Localization & Formatting
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#2196f3"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true

  assets:
    - assets/photos/
    - assets/icon/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300
    - family: Agdasima
      fonts:
        - asset: assets/fonts/Agdasima-Regular.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
